### ISSUE TITLE
Missing appicon

### ISSUE THREAD

**Issue by mickimnet** [dteoh/devdocs-macos#1]
Hello Douglas,

thank you very much for your DevDocs viewer for macOS.  There is just one small issue, I had with the app: it's missing an app icon. ;)

I took the liberty to create an appicon for you. You're free to use it, please just mention that I created it.
 
[<img width="64" alt="DevDocs.icns.zip" src="https://user-images.githubusercontent.com/2911922/50726911-a57d1680-1113-11e9-991e-aeb108ca5dd5.png">](https://github.com/dteoh/devdocs-macos/files/2729685/DevDocs.icns.zip)

Thanks and take care
Mick

PS: I've attached the icon file behind the image.

**Comment by dteoh** [comment]
Hi Mick,

Thank you very much!

I have added a new release which incorporates your icon.

I added a note about the icon in the licensing section of the readme and also in the the release notes.

**Comment by mickimnet** [comment]
Hi Douglas,

was a pleasure. Great that you like it. And thank you for the credit!

Take care
Mick
