### ISSUE TITLE
The app switches to the mobile view on hide

### ISSUE THREAD

**Issue by antelle** [dteoh/devdocs-macos#14]
Hi!
I noticed that the app switches to mobile mode after hide.

To reproduce:

1. Hide the app using <kbd>⌘H</kbd>
2. Bring it back

It reloads and switches to mobile mode, I guess, it happens [here](https://github.com/freeCodeCamp/devdocs/blob/22094f7dcf2e00823300a3e48e19b5a94bbf6ff1/assets/javascripts/views/layout/document.coffee#L43).

To fix this, I added

```javascript
app.views.Mobile.detect = () => false;
```

to `integration.js` userscript, after [this line](https://github.com/dteoh/devdocs-macos/blob/master/devdocs-macos/user-scripts/integration.js#L9). Looks like it doesn't break anything and it doesn't switch anymore, but i don't like the solution very much, it's somewhat fragile.

Thanks for the app, finally there's a working DevDocs wrapper for macOS!

**Comment by dteoh** [comment]
Thanks, I will have to investigate again, because that was the original solution which ended up breaking.

**Comment by dteoh** [comment]
It should be fixed in v0.4.3.

**Comment by antelle** [comment]
It works, thanks a lot!
