### ISSUE TITLE
White screen flash during launching

### ISSUE THREAD

**Issue by antelle** [dteoh/devdocs-macos#16]
Hi! I noticed that there's a short flash of white screen during launching, visible very well especially on dark theme:

<img width="912" alt="Screenshot 2019-09-25 at 09 01 52" src="https://user-images.githubusercontent.com/633557/65576977-3d0ce880-df73-11e9-9981-eb7277d255a5.png">

In electron this can be fixed by setting [backgroundColor](https://electronjs.org/docs/api/browser-window#setting-backgroundcolor), most likely it can be somehow done with the safari webview used here as well.

**Comment by dteoh** [comment]
Thanks for the report, fixed in v0.4.4.

**Comment by antelle** [comment]
Thank you!
