### ISSUE TITLE
customise keyboard shortcut

### ISSUE THREAD

**Issue by jeff-h** [dteoh/devdocs-macos#2]
Hi — I love what you've done with this app!

Unfortunately I dislike the default activation shortcut `option-space`. I seem to type that accidentally on occasion (eg when typing `option-8` then `space`, as you would do to write bullet points such as "• blah")

Would you be open to providing a preference to change this (eg using https://github.com/shpakovski/MASShortcut)?

If so, do you see it being added into the HTML prefs that DevDocs provides, or as a macOS preferences window? The latter would surely be much easier, but perhaps a little inconsistent given that there are prefs also inside the web app.

One other thing: it seems pretty commonplace for the same shortcut to hide the app when it's already open.

Also fantastic would be another shortcut that gets the currently-selected text from whatever app you're in, and pastes that into the DevDocs search field. It looks like this would need a custom system service though, so perhaps a bit involved.

**Comment by dteoh** [comment]
Yes, making the shortcut configurable is on my TODO list. I'll try to get it done soon-ish.

> If so, do you see it being added into the HTML prefs that DevDocs provides, or as a macOS preferences window? The latter would surely be much easier, but perhaps a little inconsistent given that there are prefs also inside the web app.

As a native window. I want to avoid injecting code into the web app unless absolutely necessary.

> One other thing: it seems pretty commonplace for the same shortcut to hide the app when it's already open.

Yeah, I forgot about this. Been using Command-H instead, which is the OS standard.

> Also fantastic would be another shortcut that gets the currently-selected text from whatever app you're in, and pastes that into the DevDocs search field. It looks like this would need a custom system service though, so perhaps a bit involved.

I did consider implementing other shortcut integrations like Alfred or Spotlight, but never actually used those features myself in Dash, so never really felt it was a must-have feature.

Maybe making it possible to trigger the app programatically is a good first step.

**Comment by jeff-h** [comment]
See https://github.com/dteoh/devdocs-macos/pull/3

I'll create a PR for the URL activation feature next time I have some down-time.
