### ISSUE TITLE
Not compatible with Catalina

### ISSUE THREAD

**Issue by levi0214** [dteoh/devdocs-macos#21]
Can't open it in MacOS 10.15.2 Catalina
Please, can anyone fix it...

**Comment by dteoh** [comment]
I'm on Catalina at work, it is working for me. Please try the "Right click -> Open" method.

**Comment by levi0214** [comment]
I can open the app, but no window displayed.
Maybe I can try to reinstall it.
BTW, are you in MacOS 10.15.2?

**Comment by dteoh** [comment]
Yes I am on 10.15.2. Can you try pressing Cmd+T? This should open a window or create a new tab.

**Comment by levi0214** [comment]
Ah, It's OK now. Thank you.
Why not open the window by default when app is clicked...

**Comment by dteoh** [comment]
It does, or at least it has always done so for me...
