### ISSUE TITLE
Close all tabs on Quit

### ISSUE THREAD

**Issue by mkozjak** [dteoh/devdocs-macos#23]
Is there a way to clear all tabs when this fine application closes (Quits)?

**Comment by dteoh** [comment]
I added a preference item to control this in v0.5.0.

**Comment by mkozjak** [comment]
@dteoh works! It now opens two tabs on startup, though. One with the needed doc and another one with tips. Any way to stop opening the tips one?

**Comment by dteoh** [comment]
Sorry, I'm not sure what you mean by tips? Can you post a screenshot of this tips tab?

**Comment by mkozjak** [comment]
Yup, when you open devdocs-macos from vim, in the first tab you get your needed doc, and on the second one you get this one: 
<img width="794" alt="image" src="https://user-images.githubusercontent.com/3506172/82032890-32d36200-969c-11ea-8833-cb305f08e3f2.png">

**Comment by dteoh** [comment]
The URL integration assumes that the app is already running. These URL events get delivered asynchronously.

On cold app start the URL events are going to race against the regular init process. At best I can push a change to delay part of the init process, but the two tab issue can and will still occur.

**Comment by mkozjak** [comment]
Ok, this implementation is good enough for me. Thanks!
