### ISSUE TITLE
App loads seemingly without css

### ISSUE THREAD

**Issue by swrobel** [dteoh/devdocs-macos#26]
Styling is totally missing. Version 0.5.0 on macOS 10.14.6. Opening new tabs has the same result.
<img width="1280" alt="Screen Shot 2020-05-19 at 9 37 45 PM" src="https://user-images.githubusercontent.com/157270/82405630-54747680-9a19-11ea-9681-f6e2dac225f0.png">

**Comment by dteoh** [comment]
Works for me on 10.14 and 10.15. When I've experienced that, it is usually a temporary issue with DevDocs service itself. This app is just a webview. Try restarting the app.

**Comment by swrobel** [comment]
Indeed this seems to be a devdocs issue: https://github.com/freeCodeCamp/devdocs/issues/1229

**Comment by swrobel** [comment]
DevDocs.io fixed the issue upstream, but if anyone else encounters this, I had to `rm -rf ~/Library/Caches/com.dteoh.devdocs-macos` before it would load correctly again.
