### ISSUE TITLE
Inability to focus search field on typing instantly after leaving iframe

### ISSUE THREAD

**Issue by Darmikon** [dteoh/devdocs-macos#27]
Hi guys.

There is a small issue with inability to focus search field on typing instantly after leaving iframe.

After typing letters inside iframe (e.g. code sample) I click outside the iframe to leave this field. 
The next letter typing should autofocus me to global search field (top left corner). 
But nothing happens except system sound signalling that the action I try to do is forbidden at the moment.
To unlock `autofocus on typing` I must click somewhere inside the body of the page outside the iframe for the second time.

The expected behaviour should be similar to [devdocs.io](https://devdocs.io/):
- I type letters inside some iframe (e.g. code sample)
- I click the page outside iframe
- The next letter typing focuses me automatically to the top left side search bar and enters the typed letter.

It would be great if this small issue is fixed someday.
Thanks

**Comment by dteoh** [comment]
This should be reported as an issue with DevDocs. Safari requires a second click, Firefox doesn't.
