### ISSUE TITLE
Feature Request: Option to import / export

### ISSUE THREAD

**Issue by chmac** [dteoh/devdocs-macos#28]
Firstly, thanks for packaging this up as a macOS app. It's awesome to be able to switch to it easily.

I noticed that when I load devdocs.io directly in brave, it frequently loses my installed docs. I started exporting my settings on a regular basis as a sort of "cheap backup". I tried clicking the "import" button in the devdocs-macos app, but it doesn't work. Also clicking the export button generates an error about no registered click handler.

So, having said all that, I realise it might be a real headache to implement. But, if it's possible, it would be awesome to have the option to export settings. Or even better, to load the settings from a designated file every time the app starts. Then I could automatically keep it in sync across multiple machines!

**Comment by dteoh** [comment]
Export and import webapp preferences enabled in v0.5.1. Not going to handle webapp preferences sync for now.

**Comment by chmac** [comment]
Awesome, thanks a lot. The import / export is excellent. Much appreciated!
