### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jeff-h** [dteoh/devdocs-macos#5]
When DevDocs is running in a browser, I think the expectation is that you would use the browser's built-in search to search inside the current document.

I miss this when using this app. Could some similar form of search be added?

**Comment by dteoh** [comment]
Not really something that I can realistically add. WKWebView doesn't expose this sort of functionality unlike the old WebView.

**Comment by jeff-h** [comment]
Wow, annoying that WKWebView doesn't expose this.

I noticed that various other Mac apps have rolled their own version, although I couldn't verify which ones are using WKWebView (is it possible to tell?).

I wonder if there's a Javascript library that emulates it? I had a good look but didn't turn up anything. I did notice that both Safari's and Chrome's Web Tools contain very similar versions, both of which I think are open-source. They would presumably be written in Javascript, although I guess the code's unlikely to be very portable.

Webkit's Web Inspector javascript:
https://trac.webkit.org/browser/webkit/branches/safari-608.1.5.1-branch/Source/WebInspectorUI#UserInterface/Views

Codemirror (used by Web Inspector) also has search javascript:
https://codemirror.net/demo/search.html

At this point I'm speaking through my hat a little so I will desist now :)

**Comment by dteoh** [comment]
Not sure which apps you looked at, but it is possible that those apps are using Electron. From my research, Electron apps can implement this easily because the APIs are exposed.

JS emulation is one option, but I'm just not interested in adding and maintaining fragile functionality. I think it is instead worth asking the DevDocs developers to consider supporting a secondary search like in Dash app, since they are already indexing all the tokens.

**Comment by jeff-h** [comment]
The non-Electron webview-based apps with their own search implementations that I looked at (just because I already had them all open) were:

* Dash (which as per above has open-sourced its implementation, although too old for this project)
* ReadKit (RSS reader) — appears to have quite a neat JS implementation
* Fluid App, another neat implementation
* Mail app, which unsurprisingly has the nice implementation that Safari has. Frustrating that they don't simple expose this in WKWebview
* Spark (email app) — the best non-Apple implementation I saw
* Paw (REST tool) — very simple implementation that might be achievable
* and even Apple's Messages app which by all accounts uses a webview in the main pane. It also has the world's most horrible search, so not much to learn there lol

I do agree with, and understand, your comment re maintaining fragile code. In my research, your native DevDocs app is rather rare, so I doubt the main DevDocs codebase would want to add this for such a unique use-case.

It seems most non-Apple apps add `<span>`'s around the matching characters, and highlighting the spans with `background-colour`. <kbd>cmd</kbd>+<kbd>g</kbd> scrolls the page so that the next span is in view. Due to the flexibility of CSS, I think there'd be numerous edge-cases where that's not going to be so great.

Apple seem to be drawing boxes on top (with a high z-index). You can see this by searching on a site with content that scrolls under the header. The apple search highlight boxes go over top of the site header.

So with all that in mind, I wonder whether it would be possible to implement something like Paw has done without it being too hacky or fragile.

If you don't have the app, unlike most apps mentioned above, it's simply adjusting the currently selected text in the webview. I know this as I checked `document.getSelection().toString()` in its web view during searching. So there's no CSS involved, and hopefully minimal JS. I'm still digging to see exactly how they've done that.

**Comment by dteoh** [comment]
Basic page searching implemented in v0.4.0.
