### ISSUE TITLE
additional url-handler suggestion

### ISSUE THREAD

**Issue by jeff-h** [dteoh/devdocs-macos#7]
When I saw the `devdocs-macos://` URL handling, it got me thinking...

I use [Browser Fairy](http://browserfairy.com) to selectively open various browsers depending on the URL. For example, all URLs beginning with `https://app.asana.com` open my Asana Fluid app.

There are several open-source projects offering much the same thing:

* [Finicky](https://github.com/johnste/finicky)
* [Browserosaurus](https://github.com/will-stone/browserosaurus)

So I was wondering, would it be possible for this app to also handle `https` URLS, but rejecting anything other than `devdocs.io`? This would make it possible for it to handle a URL like `devdocs.io/#q=keyword`.

If this was possible, in conjunction with one of the above mentioned browser selection tools, it would be trivial to repurpose an existing editor's DevDocs plugin to use your app rather than the online site.

**Comment by dteoh** [comment]
Sure, I can extend the scheme handler.

The only downside is that macOS might think that this app is a general purpose browser.

**Comment by dteoh** [comment]
> it would be trivial to repurpose an existing editor's DevDocs plugin to use your app rather than the online site.

This part, I don't think will happen, because from what I understand, it is not possible to specify both scheme + host when registering an app with macOS. Unless you use one of those "meta browser" apps you listed, the plugins will need to explicitly launch this app with the URL.

**Comment by jeff-h** [comment]
> Unless you use one of those "meta browser" apps you listed, the plugins will need to explicitly launch this app with the URL.

Correct. The whole idea hinges on the use of one of these apps, or else as you say, the plugin would need to be modified so it knows to launch this app instead of a browser.

One thing has occurred to me; people uncertain what this app does might be confused by the app handling `https` and think it's literally just opening the DevDocs website on demand inside this window — much like Fluid app would do. If you think the risk of this confusion is too high I understand!

**Comment by dteoh** [comment]
Done!

**Comment by jeff-h** [comment]
It really works! :) Using Browser Fairy and [this Sublime Text plugin](https://packagecontrol.io/packages/DevDocs) this works beautifully. Thanks for your work on it.
